### ISSUE TITLE
header zit op een rare plek

### ISSUE THREAD

**Issue by FouadTaissate** [Tristandemuijnck/the-client-case-VA#4]
https://github.com/Tristandemuijnck/the-client-case-VA/blob/6993a135d0d60ab127a2a9544e8d5418e570c970/waarneembaar.html#L14

**Comment by Tristandemuijnck** [comment]
![image](https://user-images.githubusercontent.com/43402897/194516976-9ea1b3ae-cf4c-46be-b5da-e052aa0dc836.png)

Can't replicate.
